version: 3

tasks:
  dev:
    cmds:
      - nodemon -q -e 'go' --signal SIGTERM --exec "echo '# building' && task build && echo '# build success' && ./bin/ssh-fw || exit"

  build:
    # env:
    #   CGO_ENABLED: 1
    cmds:
      - go build -o ./bin/ssh-fw main.go
